baseurl = "https://softlayer.github.io/"
languageCode = "en-us"
title = "SoftLayer API Examples"
canonifyurls = true
SectionPagesMenu = "sections"
pygmentsuseclasses = false
pygmentsStyle = "monokai"
pluralizelisttitles = "false"

[params]
  description = "SoftLayer API Examples, implementations, and release notes."
  author = "SoftLayer Evangelism Team"


[taxonomies]
	tag = "tags"
	class = "classes"

pluralizeListTitles = false

[[menu.main]]
    name = "perl"
    identifier = "perl"
    url = "/perl/"
[[menu.main]]
    name = "php"
    identifier = "php"
    url = "/php/"
[[menu.main]]
    name = "python"
    identifier = "python"
    url = "/python/"
[[menu.main]]
    name = "ruby"
    identifier = "ruby"
    url = "/ruby/"
[[menu.main]]
	name = "rest"
	identifier = "rest"
	url = "/rest/"
[[menu.main]]
    name = "tools"
    identifier = "tools"
    url = "/tools/"
[[menu.main]]
    name = "release notes"
    identifier = "release_notes"
    url = "/release_notes/"
